### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by azizsayfiddin** [cryptosvinarnik/jut.su-parser#2]
<img width="1062" alt="Screenshot 2023-01-08 at 22 25 17" src="https://user-images.githubusercontent.com/114720383/211210226-395d1446-ee4a-4fee-ac4d-07c0ab7710d3.png">

**Comment by haroke4** [comment]
I've requested a pull request where this bug is patched. You can check it if u wish =3

**Comment by cryptosvinarnik** [comment]
https://github.com/cryptosvinarnik/jut.su-parser/pull/3
